name: Auto-update
on:
  push:
    branches:
      - master

jobs:
  autoupdate:
    name: Auto-update PRs
    runs-on: ubuntu-20.04
    steps:
      - uses: docker://chinthakagodawita/autoupdate-action:v1
        env:
          GITHUB_TOKEN: "${{ secrets.NGINX_PAT }}"
          PR_READY_STATE: "ready_for_review"
          EXCLUDED_LABELS: "dependencies,no-autoupdate"
