name: Continuous Integration

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'docs/**'
      - 'examples/**'
      - 'examples-of-custom-resources/**'
      - '**.md'
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  pull_request:
    branches:
      - master
    paths-ignore:
      - 'docs/**'
      - 'examples/**'
      - 'examples-of-custom-resources/**'
      - '**.md'
    types:
      - opened
      - reopened
      - synchronize
  schedule:
    - cron:  '0 4 * * *'

defaults:
  run:
    shell: bash

env:
  K8S_VERSION: 1.22.1
  K8S_TIMEOUT: 75s
  HELM_CHART_DIR: deployments/helm-chart
  GIT_NAME: NGINX Kubernetes Team
  GIT_MAIL: kubernetes@nginx.com

jobs:

  checks:
    name: Checks and variables
    runs-on: ubuntu-20.04
    outputs:
      go_version: ${{ steps.vars.outputs.go_version }}
      go_path: ${{ steps.go.outputs.go_path }}
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Output Variables
        id: vars
        run: |
          echo "::set-output name=go_version::$(grep "go 1." go.mod | cut -d " " -f 2)"
      - name: Setup Golang Environment
        uses: actions/setup-go@v2
        with:
          go-version: ${{ steps.vars.outputs.go_version }}
      - name: Determine GOPATH
        id: go
        run: echo "::set-output name=go_path::$(go env GOPATH)"
      - name: Check if CRDs changed
        run: |
          make update-crds && git diff --name-only --exit-code deployments/common/crds* deployments/helm-chart/crds*
      - name: Check if Codegen changed
        run: |
          make update-codegen && git diff --name-only --exit-code pkg/**/zz_generated.deepcopy.go

  binary:
    name: Build binary
    runs-on: ubuntu-20.04
    needs: checks
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Golang Environment
        uses: actions/setup-go@v2
        with:
          go-version: ${{ needs.checks.outputs.go_version }}
      - name: Build binary
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: build --snapshot --rm-dist --id kubernetes-ingress --single-target
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GOPATH: ${{ needs.check.outputs.go_path }}
      - name: Store Artifacts in Cache
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/dist
          key: nginx-ingress-${{ github.run_id }}-${{ github.run_number }}-single

  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-20.04
    needs: checks
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Setup Golang Environment
        uses: actions/setup-go@v2
        with:
          go-version: ${{ needs.checks.outputs.go_version }}
      - name: Run Tests
        run: go test ./...

  setup-matrix:
    name: Setup Matrix for Smoke Tests
    runs-on: ubuntu-20.04
    needs: [binary, unit-tests]
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - id: set-matrix
        run: |
          if [ "${{ github.event_name }}" != "schedule" ]; then
            echo "::set-output name=matrix::{\"images\": \
                                                [{\"image\": \"debian\", \"marker\": \"ingresses\"}, \
                                                {\"image\": \"alpine\", \"marker\":\"vsr\"}, \
                                                {\"image\": \"opentracing\", \"marker\": \"vs\"}, \
                                                {\"image\": \"ubi\", \"marker\": \"ts\"}, \
                                                {\"image\": \"debian\", \"marker\": \"policies\"}]}"
          else
            echo "::set-output name=matrix::{\"k8s\": [\"1.19.11\", \"1.20.7\", \"1.21.2\", \"1.22.1\"]}"
          fi

  smoke-tests:
    name: Smoke Tests
    runs-on: ubuntu-20.04
    needs: setup-matrix
    strategy:
      matrix: ${{ fromJSON(needs.setup-matrix.outputs.matrix) }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Run Smoke Tests
        id: smoke-tests
        uses: ./.github/actions/smoke-tests
        with:
          image: ${{ matrix.images.image != '' && matrix.images.image || 'debian' }}
          marker: ${{ matrix.images.marker != '' && matrix.images.marker || '""' }}
          k8s-version: ${{ matrix.k8s != '' && matrix.k8s || env.K8S_VERSION }}
      - name: Upload Test Results
        uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.smoke-tests.outputs.test-results-name }}
          path: ${{ github.workspace }}/tests/${{ steps.smoke-tests.outputs.test-results-name }}.html
        if: always()

  helm-tests:
    name: Helm Tests
    runs-on: ubuntu-20.04
    needs: [binary, unit-tests]
    env:
      NGINX_HTTP_PORT: 8080
      NGINX_HTTPS_PORT: 8443
      HELM_TEST_RETRIES: 5
      HELM_HTTP_POSTFIX: s
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Fetch Cached Artifacts
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/dist
          key: nginx-ingress-${{ github.run_id }}-${{ github.run_number }}-single
      - name: Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build Docker Image nginx-ingress
        uses: docker/build-push-action@v2
        with:
          file: build/Dockerfile
          context: '.'
          # Disable cache until https://github.com/docker/buildx/issues/681 is fixed
          # cache-from: type=gha
          # cache-to: type=gha,mode=max
          target: goreleaser
          tags: nginx-ingress:${{ github.sha }}
          load: true
          build-args: BUILD_OS=debian
      - name: Deploy Kubernetes
        id: k8s
        run: |
          kind create cluster --name ${{ github.run_id }} --image=kindest/node:v${{ env.K8S_VERSION }} --wait ${{ env.K8S_TIMEOUT }}
          kind load docker-image nginx-ingress:${{ github.sha }} --name ${{ github.run_id }}
      - name: Install Chart
        run: >
          helm install
          oss
          .
          --set controller.image.repository=nginx-ingress
          --set controller.image.tag=${{ github.sha }}
          --set controller.service.type=NodePort
          --set controller.nginxplus=false
          --wait
        working-directory: ${{ github.workspace }}/deployments/helm-chart
      - name: Expose Test Ingresses
        run: |
          kubectl port-forward service/oss-nginx-ingress ${{ env.NGINX_HTTP_PORT }}:80 &
          kubectl port-forward service/oss-nginx-ingress ${{ env.NGINX_HTTPS_PORT }}:443 &
      - name: Test HTTP
        run: |
          . tests/ci-files/helm-http-test.sh ${{ env.HELM_TEST_RETRIES }} ${{ env.NGINX_HTTP_PORT }}
      - name: Test HTTPS
        run: |
          . tests/ci-files/helm-http-test.sh ${{ env.HELM_TEST_RETRIES }} ${{ env.NGINX_HTTPS_PORT }} ${{ env.HELM_HTTP_POSTFIX }}

  build-binaries:
    name: Build Binaries
    runs-on: ubuntu-20.04
    needs: [checks, smoke-tests]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Golang Environment
        uses: actions/setup-go@v2
        with:
          go-version: ${{ needs.checks.outputs.go_version }}
      - name: Build binaries
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: build --rm-dist --id kubernetes-ingress ${{ github.event_name == 'pull_request' && '--single-target' || '' }} ${{ !startsWith(github.ref, 'refs/tags/') && '--snapshot' || '' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GOPATH: ${{ needs.check.outputs.go_path }}
      - name: Store Artifacts in Cache
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/dist
          key: nginx-ingress-${{ github.run_id }}-${{ github.run_number }}-multi

  build-docker:
    name: Build Docker Images
    runs-on: ubuntu-20.04
    needs: build-binaries
    strategy:
      matrix:
        include:
          - type: debian
            suffix: ''
            platforms: linux/arm,linux/arm64,linux/amd64,linux/ppc64le,linux/s390x
          - type: alpine
            suffix: '-alpine'
            platforms: linux/arm,linux/arm64,linux/amd64,linux/ppc64le,linux/s390x
          - type: ubi
            suffix: '-ubi'
            platforms: linux/arm64,linux/amd64
          - type: opentracing
            suffix: '-ot'
            platforms: linux/arm,linux/arm64,linux/amd64,linux/ppc64le,linux/s390x
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Fetch Cached Artifacts
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/dist
          key: nginx-ingress-${{ github.run_id }}-${{ github.run_number }}-multi
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: arm,arm64,ppc64le,s390x
        if: github.event_name != 'pull_request'
      - name: Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: DockerHub Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        if: github.event_name != 'pull_request'
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: nginx/nginx-ingress
          flavor: suffix=${{ matrix.suffix }}
          tags: |
            type=edge
            type=ref,event=pr
            type=schedule
            type=semver,pattern={{version}}
          labels: |
            org.opencontainers.image.description=NGINX Ingress Controller for Kubernetes
            org.opencontainers.image.documentation=https://docs.nginx.com/nginx-ingress-controller
            org.opencontainers.image.vendor=NGINX Inc <kubernetes@nginx.com>
      - name: Output Variables
        id: var
        run: |
          version=${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.version'] }}
          if ${{ startsWith(github.ref, 'refs/tags/') }}; then
              ic_version=v$version
          else
              tag=$(git describe --tags --abbrev=0)
              sha_short=$(echo ${{ github.sha }} | cut -c1-7)
              ic_version=$tag-$version-$sha_short
          fi
          echo "::set-output name=ic_version::$ic_version"
      - name: Build Docker images (and push to Dockerhub if not a PR)
        uses: docker/build-push-action@v2
        with:
          file: build/Dockerfile
          context: '.'
          # Disable cache until https://github.com/docker/buildx/issues/681 is fixed
          # cache-from: type=gha
          # cache-to: type=gha,mode=max
          target: goreleaser
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: ${{ github.event_name != 'pull_request' && matrix.platforms || '' }}
          load: ${{ github.event_name == 'pull_request' }}
          push: ${{ github.event_name != 'pull_request' }}
          pull: true
          build-args: |
            BUILD_OS=${{ matrix.type }}
            IC_VERSION=${{ steps.var.outputs.ic_version }}
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: nginx/nginx-ingress:${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.version'] }}
          format: 'template'
          template: '@/contrib/sarif.tpl'
          output: 'trivy-results-${{ matrix.type }}.sarif'
          ignore-unfixed: 'true'
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: 'trivy-results-${{ matrix.type }}.sarif'
      - name: Upload Scan Results
        uses: actions/upload-artifact@v2
        with:
          name: 'trivy-results-${{ matrix.type }}.sarif'
          path: 'trivy-results-${{ matrix.type }}.sarif'
        if: always()

  package-helm:
    name: Package Helm Chart
    runs-on: ubuntu-20.04
    needs: [build-docker, helm-tests]
    outputs:
      version: ${{ steps.var.outputs.helm_version }}
      type: ${{ steps.var.outputs.helm_type }}
    if: github.event_name == 'push'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Output Variables
        id: var
        run: |
          if ${{ startsWith(github.ref, 'refs/tags/') }}; then
              helm_version="$(helm show chart ${{ env.HELM_CHART_DIR }} | grep 'version:' | cut -d ' ' -f 2)"
              helm_type="stable"
          else
              helm_version="0.0.0-edge"
              helm_type="edge"
          fi
          echo "::set-output name=helm_version::$helm_version"
          echo "::set-output name=helm_type::$helm_type"
      - name: Lint
        run: helm lint ${{ env.HELM_CHART_DIR }}
      - name: Package
        run: helm package --version ${{ steps.var.outputs.helm_version }} ${{ env.HELM_CHART_DIR }}
      - name: Upload Chart
        uses: actions/upload-artifact@v2
        with:
          name: helm-chart
          path: ${{ github.workspace }}/nginx-ingress-${{ steps.var.outputs.helm_version }}.tgz

  release-helm:
    name: Release Helm Chart
    runs-on: ubuntu-20.04
    needs: package-helm
    if: github.event_name == 'push'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          repository: nginxinc/helm-charts
          fetch-depth: 1
          token: ${{ secrets.NGINX_PAT }}
      - name: Remove previous Chart
        run: rm -f ${{ github.workspace }}/${{ needs.package-helm.outputs.type }}/nginx-ingress-${{ needs.package-helm.outputs.version }}.tgz
      - name: Retrieve latest Helm Chart
        uses: actions/download-artifact@v2
        with:
          name: helm-chart
          path: ${{ github.workspace }}/${{ needs.package-helm.outputs.type }}
      - name: Push Helm Chart
        run: |
          helm repo index ${{ needs.package-helm.outputs.type }} --url https://helm.nginx.com/${{ needs.package-helm.outputs.type }}
          git add -A
          git -c user.name='${{ env.GIT_NAME }}' -c user.email='${{ env.GIT_MAIL }}' \
          commit -m "NGINX Ingress Controller - Release ${{ needs.package-helm.outputs.type }} ${{ needs.package-helm.outputs.version }}"
          git push -u origin master

  publish-release-notes:
    name: Publish Release Notes
    runs-on: ubuntu-20.04
    needs: release-helm
    if: ${{ startsWith(github.ref, 'refs/tags/') }}
    steps:
      - name: Publish Release Notes
        uses: release-drafter/release-drafter@v5
        with:
            publish: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
