name: Fossa

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'docs/**'
      - 'examples/**'
      - 'examples-of-custom-resources/**'
      - '**.md'

jobs:

  scan:
    name: Fossa
    runs-on: ubuntu-20.04
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Scan
        uses: fossas/fossa-action@v1
        with:
          api-key: ${{ secrets.FOSSA_TOKEN }}
