# https://kubernetes.io/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata:
  name: service1
  namespace: default
spec:
  selector:
    app: myjob
  type: LoadBalancer
  ports:
  - name: myjob
    protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30001
---
# https://kubernetes.io/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata:
  name: service2
  namespace: default
spec:
  selector:
    app: test
  type: LoadBalancer
  ports:
  - name: myjob
    protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30002
---
