apiVersion: v1
kind: Service
metadata:
  name: testwebsvc
  #namespace: testweb
spec:
  externalTrafficPolicy: Local
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 1234
    protocol: TCP
    name: http
  selector:
    app: testweb
